version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cloudformation,s3,ec2
    volumes:
      - ./localstack/bootstrap:/opt/bootstrap/
      - ./localstack/data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
