name: Dynamic Test Execution
on: [push]
jobs:
  prepare-execution-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Prepare Execution Matrix
        id: set-matrix
        run: |
          EXEC_FILES=$(find tests -type f -executable | jq -R -s -c 'split("\n")[:-1]')
          echo 'MATRIX<<EOF' >> $GITHUB_OUTPUT
          echo $EXEC_FILES >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.MATRIX }}
  execute-scripts:
    needs: prepare-execution-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: ${{ fromJson(needs.prepare-execution-matrix.outputs.matrix) }}
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: "s3,ec2,cloudformation"
          DEFAULT_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: "test"
          AWS_SECRET_ACCESS_KEY: "test"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Execute Script
        run: ./tests/${{ matrix.script }}
